stages:
  data_cleaning:
    cmd: python spotify_recommender/content_based_filtering/data_cleaning.py
    deps:
      - spotify_recommender/content_based_filtering/data_cleaning.py
      - data/raw/Music_Info.csv
    outs:
      - data/interim/Music_Info_cleaned.csv

  data_preparation_cbf:
    cmd: python spotify_recommender/content_based_filtering/data_preparation.py
    deps:
      - spotify_recommender/content_based_filtering/data_preparation.py
      - data/interim/Music_Info_cleaned.csv
    outs:
      - data/interim/Music_Info_cleaned_CBF.csv

  data_transformation_cbf:
    cmd: python spotify_recommender/content_based_filtering/data_transformation.py
    deps:
      - spotify_recommender/content_based_filtering/data_transformation.py
      - data/interim/Music_Info_cleaned_CBF.csv
    outs:
      - data/processed/Music_Info_cleaned_transformed_CBF.npz
      - models/trained_transformer_CBF.joblib

  content_based_filtering:
    cmd: python spotify_recommender/content_based_filtering/recommendation.py
    deps:
      - spotify_recommender/content_based_filtering/recommendation.py
      - data/interim/Music_Info_cleaned.csv
      - data/processed/Music_Info_cleaned_transformed_CBF.npz
