stages:
  data_cleaning:
    cmd: python spotify_recommender/data_cleaning.py
    deps:
      - spotify_recommender/data_cleaning.py
      - data/raw/Music_Info.csv
    outs:
      - data/interim/Music_Info_cleaned.csv
  
  data_preparation_cbf:
    cmd: python spotify_recommender/content_based_filtering_data_prep.py
    deps:
      - spotify_recommender/content_based_filtering_data_prep.py
      - data/interim/Music_Info_cleaned.csv
    outs:
      - data/interim/Music_Info_cleaned_CBF.csv