stages:
  data_cleaning:
    cmd: python spotify_recommender/data_cleaning.py
    deps:
      - spotify_recommender/data_cleaning.py
      - data/raw/Music_Info.csv
    outs:
      - data/interim/Music_Info.csv